About: This Notebook will be mainly used for the capstone project.

Final Assignment Week 3 Data Science Capstone

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from unicodedata import normalize

In [2]:
table = pd.read_html('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M')

In [3]:
print(f'Total tables: {len(table)}')

Total tables: 3

In [4]:
table = pd.read_html('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M', match='Postal Code')
len(table)

1

In [5]:
df = table[0]
df.head(15)

   Postal Code           Borough                                Neighbourhood
0          M1A      Not assigned                                 Not assigned
1          M2A      Not assigned                                 Not assigned
2          M3A        North York                                    Parkwoods
3          M4A        North York                             Victoria Village
4          M5A  Downtown Toronto                    Regent Park, Harbourfront
5          M6A        North York             Lawrence Manor, Lawrence Heights
6          M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government
7          M8A      Not assigned                                 Not assigned
8          M9A         Etobicoke      Islington Avenue, Humber Valley Village
9          M1B       Scarborough                               Malvern, Rouge
10         M2B      Not assigned                                 Not assigned
11         M3B        North York                                    Don Mills
12         M4B         East York              Parkview Hill, Woodbine Gardens
13         M5B  Downtown Toronto                     Garden District, Ryerson
14         M6B        North York                                    Glencairn

In [6]:
df.drop(df.index[df['Borough'] == 'Not assigned'], inplace = True)

# Reset Index
df = df.reset_index(drop=True)

df.head()

  Postal Code           Borough                                Neighbourhood
0         M3A        North York                                    Parkwoods
1         M4A        North York                             Victoria Village
2         M5A  Downtown Toronto                    Regent Park, Harbourfront
3         M6A        North York             Lawrence Manor, Lawrence Heights
4         M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [7]:
df = df.groupby(['Postal Code', 'Borough'])['Neighbourhood'].apply(', '.join).reset_index()

df.head(50)

,Postal Code,Borough,Neighbourhood
0,M1B,Scarborough,"Malvern, Rouge"
1,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek"
2,M1E,Scarborough,"Guildwood, Morningside, West Hill"
3,M1G,Scarborough,Woburn
4,M1H,Scarborough,Cedarbrae
5,M1J,Scarborough,Scarborough Village
6,M1K,Scarborough,"Kennedy Park, Ionview, East Birchmount Park"
7,M1L,Scarborough,"Golden Mile, Clairlea, Oakridge"
8,M1M,Scarborough,"Cliffside, Cliffcrest, Scarborough Village West"
9,M1N,Scarborough,"Birch Cliff, Cliffside West"
10,M1P,Scarborough,"Dorset Park, Wexford Heights, Scarborough Town..."
11,M1R,Scarborough,"Wexford, Maryvale"
12,M1S,Scarborough,Agincourt
13,M1T,Scarborough,"Clarks Corners, Tam O'Shanter, Sullivan"
14,M1V,Scarborough,"Milliken, Agincourt North, Steeles East, L'Amo..."
15,M1W,Scarborough,"Steeles West, L'Amoreaux West"
16,M1X,Scarborough,Upper Rouge
17,M2H,North York,Hillcrest Village
18,M2J,North York,"Fairview, Henry Farm, Oriole"
19,M2K,North York,Bayview Village
20,M2L,North York,"York Mills, Silver Hills"
21,M2M,North York,"Willowdale, Newtonbrook"
22,M2N,North York,"Willowdale, Willowdale East"
23,M2P,North York,York Mills West
24,M2R,North York,"Willowdale, Willowdale West"
25,M3A,North York,Parkwoods
26,M3B,North York,Don Mills
27,M3C,North York,Don Mills
28,M3H,North York,"Bathurst Manor, Wilson Heights, Downsview North"
29,M3J,North York,"Northwood Park, York University"
30,M3K,North York,Downsview
31,M3L,North York,Downsview
32,M3M,North York,Downsview
33,M3N,North York,Downsview
34,M4A,North York,Victoria Village
35,M4B,East York,"Parkview Hill, Woodbine Gardens"
36,M4C,East York,Woodbine Heights
37,M4E,East Toronto,The Beaches
38,M4G,East York,Leaside
39,M4H,East York,Thorncliffe Park
40,M4J,East York,"East Toronto, Broadview North (Old East York)"
41,M4K,East Toronto,"The Danforth West, Riverdale"
42,M4L,East Toronto,"India Bazaar, The Beaches West"
43,M4M,East Toronto,Studio District
44,M4N,Central Toronto,Lawrence Park
45,M4P,Central Toronto,Davisville North
46,M4R,Central Toronto,"North Toronto West, Lawrence Park"
47,M4S,Central Toronto,Davisville
48,M4T,Central Toronto,"Moore Park, Summerhill East"
49,M4V,Central Toronto,"Summerhill West, Rathnelly, South Hill, Forest..."

In [8]:
df.loc[df['Neighbourhood'] == 'Not assigned', 'Neighbourhood'] = df['Borough']

df.head()

  Postal Code      Borough                           Neighbourhood
0         M1B  Scarborough                          Malvern, Rouge
1         M1C  Scarborough  Rouge Hill, Port Union, Highland Creek
2         M1E  Scarborough       Guildwood, Morningside, West Hill
3         M1G  Scarborough                                  Woburn
4         M1H  Scarborough                               Cedarbrae

In [9]:
df.to_csv(r'df_wiki.csv')

In [10]:
url = "http://cocl.us/Geospatial_data"
df1 = pd.read_csv(url)

df1.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [11]:
df2 = pd.merge(df, df1, left_on = 'Postal Code', right_on = 'Postal Code', how = 'left')


df2.head()

,Postal Code,Borough,Neighbourhood,Latitude,Longitude
0,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
1,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476

In [12]:
df2.to_csv(r'df_geo.csv')